//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAPET.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetaActivity))]
    public partial class Activity
    {
        public string ActivityNo { get; set; }
        public string AdmNo { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public byte[] Photo { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Deadline { get; set; }
        public string ImageMimeType { get; set; }
    
        public virtual Adm Adm { get; set; }
    }
}
