//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAPET.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetaLost))]
    public partial class Lost
    {
        public string LostNo { get; set; }
        public byte[] Photo { get; set; }
        public string Name { get; set; }
        public string SpeciesNo { get; set; }
        public string GenderNo { get; set; }
        public string SizeNo { get; set; }
        public string Color { get; set; }
        public string Age { get; set; }
        public System.DateTime Time { get; set; }
        public string Place { get; set; }
        public string ContactPerson { get; set; }
        public string Contact { get; set; }
        public string Details { get; set; }
        public string ChipNumber { get; set; }
        public int UserNo { get; set; }
        public string CityNo { get; set; }
        public System.DateTime Date { get; set; }
        public string ImageMimeType { get; set; }
    
        public virtual City City { get; set; }
        public virtual PetGender PetGender { get; set; }
        public virtual PetSize PetSize { get; set; }
        public virtual Species Species { get; set; }
        public virtual User User { get; set; }
    }
}
