//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAPET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hw_MyPetsEntities : DbContext
    {
        public Hw_MyPetsEntities()
            : base("name=Hw_MyPetsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Adm> Adm { get; set; }
        public virtual DbSet<Adopt> Adopt { get; set; }
        public virtual DbSet<Black> Black { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Follow> Follow { get; set; }
        public virtual DbSet<FormDetail> FormDetail { get; set; }
        public virtual DbSet<Freeze> Freeze { get; set; }
        public virtual DbSet<From> From { get; set; }
        public virtual DbSet<Introduction> Introduction { get; set; }
        public virtual DbSet<Knowledge> Knowledge { get; set; }
        public virtual DbSet<Like> Like { get; set; }
        public virtual DbSet<Lost> Lost { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<MsgReport> MsgReport { get; set; }
        public virtual DbSet<PetGender> PetGender { get; set; }
        public virtual DbSet<PetSize> PetSize { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostState> PostState { get; set; }
        public virtual DbSet<PostType> PostType { get; set; }
        public virtual DbSet<Problem> Problem { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<ResetUserPwd> ResetUserPwd { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
